[package]
name = "axion"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_yaml = "*"
csv = "*"
tempfile = "*"
rayon = "*"
criterion = "*"

[[bench]]
name = "series_apply_benchmark"
harness = false
